<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RoomsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('rooms')->delete();
        
        \DB::table('rooms')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'CC-30',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'CC-32',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'CC-55',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => '401',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => '401 A',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => '402',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => '403',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => '403-B',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => '403-C',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => '403-D',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => '403-E',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => '404',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => '405',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => '406',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => '407',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => '408',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => '409',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => '410',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => '411',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => '412',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => '413',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => '414',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => '415',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => '416',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => '417',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => '418',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => '419',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => '420',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => '421',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => '422',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => '423',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => '424',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => '425',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => '426',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => '427',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => '428',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => '429',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => '430',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => '501',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => '502',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => '503',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => '504',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => '505',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => '506',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => '507',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => '508',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => '509',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => '510',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => '511',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => '512',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => '513',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => '514',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => '515',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => '516',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            54 => 
            array (
                'id' => 55,
                'name' => '517',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => '518',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => '519',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => '520',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => '521',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => '522',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => '523',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => '524',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => '525',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            63 => 
            array (
                'id' => 64,
                'name' => '526',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            64 => 
            array (
                'id' => 65,
                'name' => '527',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            65 => 
            array (
                'id' => 66,
                'name' => '528',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            66 => 
            array (
                'id' => 67,
                'name' => '529',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            67 => 
            array (
                'id' => 68,
                'name' => '530',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            68 => 
            array (
                'id' => 69,
                'name' => '531',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            69 => 
            array (
                'id' => 70,
                'name' => '532',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            70 => 
            array (
                'id' => 71,
                'name' => '533',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            71 => 
            array (
                'id' => 72,
                'name' => '534',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            72 => 
            array (
                'id' => 73,
                'name' => '535',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            73 => 
            array (
                'id' => 74,
                'name' => '536',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            74 => 
            array (
                'id' => 75,
                'name' => '537',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            75 => 
            array (
                'id' => 76,
                'name' => '538',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            76 => 
            array (
                'id' => 77,
                'name' => '539',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            77 => 
            array (
                'id' => 78,
                'name' => '540',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            78 => 
            array (
                'id' => 79,
                'name' => '601',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            79 => 
            array (
                'id' => 80,
                'name' => '604',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            80 => 
            array (
                'id' => 81,
                'name' => '605',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            81 => 
            array (
                'id' => 82,
                'name' => '606',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            82 => 
            array (
                'id' => 83,
                'name' => '608',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            83 => 
            array (
                'id' => 84,
                'name' => '609',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            84 => 
            array (
                'id' => 85,
                'name' => '610',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            85 => 
            array (
                'id' => 86,
                'name' => '611',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            86 => 
            array (
                'id' => 87,
                'name' => '615',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            87 => 
            array (
                'id' => 88,
                'name' => '616',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            88 => 
            array (
                'id' => 89,
                'name' => '617',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            89 => 
            array (
                'id' => 90,
                'name' => '619',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            90 => 
            array (
                'id' => 91,
                'name' => '621',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            91 => 
            array (
                'id' => 92,
                'name' => '624',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            92 => 
            array (
                'id' => 93,
                'name' => '625',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            93 => 
            array (
                'id' => 94,
                'name' => '626',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            94 => 
            array (
                'id' => 95,
                'name' => '628',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            95 => 
            array (
                'id' => 96,
                'name' => '629',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            96 => 
            array (
                'id' => 97,
                'name' => '630',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            97 => 
            array (
                'id' => 98,
                'name' => '632',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            98 => 
            array (
                'id' => 99,
                'name' => '633',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            99 => 
            array (
                'id' => 100,
                'name' => '635',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            100 => 
            array (
                'id' => 101,
                'name' => '636',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            101 => 
            array (
                'id' => 102,
                'name' => '637',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            102 => 
            array (
                'id' => 103,
                'name' => '638',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            103 => 
            array (
                'id' => 104,
                'name' => '639',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            104 => 
            array (
                'id' => 105,
                'name' => '701',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            105 => 
            array (
                'id' => 106,
                'name' => '702',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            106 => 
            array (
                'id' => 107,
                'name' => '704',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            107 => 
            array (
                'id' => 108,
                'name' => '705',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            108 => 
            array (
                'id' => 109,
                'name' => '706',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            109 => 
            array (
                'id' => 110,
                'name' => '707',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            110 => 
            array (
                'id' => 111,
                'name' => '708',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            111 => 
            array (
                'id' => 112,
                'name' => '711',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            112 => 
            array (
                'id' => 113,
                'name' => '712',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            113 => 
            array (
                'id' => 114,
                'name' => '713',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            114 => 
            array (
                'id' => 115,
                'name' => '715',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            115 => 
            array (
                'id' => 116,
                'name' => '716',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            116 => 
            array (
                'id' => 117,
                'name' => '717',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            117 => 
            array (
                'id' => 118,
                'name' => '720',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            118 => 
            array (
                'id' => 119,
                'name' => '721',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            119 => 
            array (
                'id' => 120,
                'name' => '722',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            120 => 
            array (
                'id' => 121,
                'name' => '723',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            121 => 
            array (
                'id' => 122,
                'name' => '724',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            122 => 
            array (
                'id' => 123,
                'name' => '725',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            123 => 
            array (
                'id' => 124,
                'name' => '728',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            124 => 
            array (
                'id' => 125,
                'name' => '729',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            125 => 
            array (
                'id' => 126,
                'name' => '730',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            126 => 
            array (
                'id' => 127,
                'name' => '731',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            127 => 
            array (
                'id' => 128,
                'name' => '733',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            128 => 
            array (
                'id' => 129,
                'name' => '734',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            129 => 
            array (
                'id' => 130,
                'name' => '735',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            130 => 
            array (
                'id' => 131,
                'name' => '736',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            131 => 
            array (
                'id' => 132,
                'name' => '738',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            132 => 
            array (
                'id' => 133,
                'name' => '739',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            133 => 
            array (
                'id' => 134,
                'name' => '740',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            134 => 
            array (
                'id' => 135,
                'name' => '801',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            135 => 
            array (
                'id' => 136,
                'name' => '805',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            136 => 
            array (
                'id' => 137,
                'name' => '806',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            137 => 
            array (
                'id' => 138,
                'name' => '815',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            138 => 
            array (
                'id' => 139,
                'name' => '829',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            139 => 
            array (
                'id' => 140,
                'name' => '830',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            140 => 
            array (
                'id' => 141,
                'name' => '833',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            141 => 
            array (
                'id' => 142,
                'name' => '834',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            142 => 
            array (
                'id' => 143,
                'name' => '835',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            143 => 
            array (
                'id' => 144,
                'name' => '836',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            144 => 
            array (
                'id' => 145,
                'name' => 'B-12',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => '2025-08-06 14:25:39',
                'floor_id' => 3,
            ),
            145 => 
            array (
                'id' => 146,
                'name' => 'B-14',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            146 => 
            array (
                'id' => 147,
                'name' => 'B-15',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            147 => 
            array (
                'id' => 148,
                'name' => 'B-16',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            148 => 
            array (
                'id' => 149,
                'name' => 'B-17',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            149 => 
            array (
                'id' => 150,
                'name' => 'B-18',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            150 => 
            array (
                'id' => 151,
                'name' => 'B-19',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            151 => 
            array (
                'id' => 152,
                'name' => 'B-20',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            152 => 
            array (
                'id' => 153,
                'name' => 'B-22',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            153 => 
            array (
                'id' => 154,
                'name' => 'B-23',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            154 => 
            array (
                'id' => 155,
                'name' => 'B-27',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            155 => 
            array (
                'id' => 156,
                'name' => 'B-28',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            156 => 
            array (
                'id' => 157,
                'name' => 'B-30',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            157 => 
            array (
                'id' => 158,
                'name' => 'B-33',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            158 => 
            array (
                'id' => 159,
                'name' => 'B-34',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            159 => 
            array (
                'id' => 160,
                'name' => 'B-35',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            160 => 
            array (
                'id' => 161,
                'name' => 'B-37',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            161 => 
            array (
                'id' => 162,
                'name' => 'A-38',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            162 => 
            array (
                'id' => 163,
            'name' => 'B-42(A)',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            163 => 
            array (
                'id' => 164,
                'name' => 'B-44',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            164 => 
            array (
                'id' => 165,
                'name' => 'B-47',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            165 => 
            array (
                'id' => 166,
                'name' => 'B-54',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            166 => 
            array (
                'id' => 167,
                'name' => 'B-56-A',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            167 => 
            array (
                'id' => 168,
                'name' => 'B-57',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            168 => 
            array (
                'id' => 169,
                'name' => 'B-58',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            169 => 
            array (
                'id' => 170,
                'name' => 'B-59',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            170 => 
            array (
                'id' => 171,
                'name' => 'B-60',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            171 => 
            array (
                'id' => 172,
                'name' => 'B-61',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            172 => 
            array (
                'id' => 173,
                'name' => 'B-62',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            173 => 
            array (
                'id' => 174,
                'name' => 'B-63',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            174 => 
            array (
                'id' => 175,
                'name' => 'B-64',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            175 => 
            array (
                'id' => 176,
                'name' => 'B-65',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            176 => 
            array (
                'id' => 177,
                'name' => 'B-66',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            177 => 
            array (
                'id' => 178,
                'name' => 'B-67',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            178 => 
            array (
                'id' => 179,
                'name' => 'B-68',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            179 => 
            array (
                'id' => 180,
                'name' => 'B-68A',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            180 => 
            array (
                'id' => 181,
                'name' => 'B-70-A',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            181 => 
            array (
                'id' => 182,
                'name' => '101',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            182 => 
            array (
                'id' => 183,
                'name' => '102',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            183 => 
            array (
                'id' => 184,
                'name' => '104',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            184 => 
            array (
                'id' => 185,
                'name' => '105',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            185 => 
            array (
                'id' => 186,
                'name' => '112',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            186 => 
            array (
                'id' => 187,
                'name' => '201',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            187 => 
            array (
                'id' => 188,
                'name' => '202',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            188 => 
            array (
                'id' => 189,
                'name' => '203',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            189 => 
            array (
                'id' => 190,
                'name' => 'D-205',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            190 => 
            array (
                'id' => 191,
                'name' => '208',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            191 => 
            array (
                'id' => 192,
                'name' => '209',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            192 => 
            array (
                'id' => 193,
                'name' => '212',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            193 => 
            array (
                'id' => 194,
                'name' => '301',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            194 => 
            array (
                'id' => 195,
                'name' => '302',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            195 => 
            array (
                'id' => 196,
                'name' => '303',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            196 => 
            array (
                'id' => 197,
                'name' => 'B-304',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            197 => 
            array (
                'id' => 198,
                'name' => '305',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            198 => 
            array (
                'id' => 199,
                'name' => '306',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            199 => 
            array (
                'id' => 200,
                'name' => '308',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            200 => 
            array (
                'id' => 201,
                'name' => '313',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            201 => 
            array (
                'id' => 202,
                'name' => 'C-401',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            202 => 
            array (
                'id' => 203,
                'name' => 'C-402',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            203 => 
            array (
                'id' => 204,
                'name' => 'D-401',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            204 => 
            array (
                'id' => 205,
                'name' => 'D-402',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            205 => 
            array (
                'id' => 206,
                'name' => 'D-403',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            206 => 
            array (
                'id' => 207,
                'name' => 'D-404',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            207 => 
            array (
                'id' => 208,
                'name' => 'D-405',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            208 => 
            array (
                'id' => 209,
                'name' => 'D-406',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            209 => 
            array (
                'id' => 210,
                'name' => 'D-407',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            210 => 
            array (
                'id' => 211,
                'name' => 'D-408',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            211 => 
            array (
                'id' => 212,
                'name' => 'D-409',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            212 => 
            array (
                'id' => 213,
                'name' => 'D-410',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            213 => 
            array (
                'id' => 214,
                'name' => 'D-411',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            214 => 
            array (
                'id' => 215,
                'name' => 'D-411-A',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            215 => 
            array (
                'id' => 216,
                'name' => 'D-412',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            216 => 
            array (
                'id' => 217,
                'name' => 'D-413',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            217 => 
            array (
                'id' => 218,
                'name' => 'E-405',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 6,
            ),
            218 => 
            array (
                'id' => 219,
                'name' => '6',
                'block' => 'Nila',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            219 => 
            array (
                'id' => 220,
                'name' => '100',
                'block' => 'Nila',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            220 => 
            array (
                'id' => 221,
                'name' => '4',
                'block' => 'Nila',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            221 => 
            array (
                'id' => 222,
                'name' => '14',
                'block' => 'Nila',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            222 => 
            array (
                'id' => 223,
                'name' => '8',
                'block' => 'Nila',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            223 => 
            array (
                'id' => 224,
                'name' => '7',
                'block' => 'Nila',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            224 => 
            array (
                'id' => 225,
                'name' => '14-A',
                'block' => 'Nila',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            225 => 
            array (
                'id' => 226,
                'name' => '73',
                'block' => 'Nila',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 5,
            ),
            226 => 
            array (
                'id' => 227,
                'name' => '41-B',
                'block' => 'Nila',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            227 => 
            array (
                'id' => 228,
                'name' => '18',
                'block' => 'Nila',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            228 => 
            array (
                'id' => 229,
                'name' => '28-A',
                'block' => 'Nila',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            229 => 
            array (
                'id' => 230,
                'name' => '35-A',
                'block' => 'Nila',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            230 => 
            array (
                'id' => 231,
                'name' => '22-B',
                'block' => 'Nila',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 3,
            ),
            231 => 
            array (
                'id' => 232,
                'name' => '36',
                'block' => 'Nila',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 4,
            ),
            232 => 
            array (
                'id' => 233,
                'name' => 'Museum',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'floor_id' => 2,
            ),
            233 => 
            array (
                'id' => 234,
                'name' => 'Reception',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 4,
                'created_at' => '2025-08-08 09:36:54',
                'updated_at' => '2025-08-08 09:36:54',
                'floor_id' => 2,
            ),
            234 => 
            array (
                'id' => 235,
                'name' => '818',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => '2025-08-08 09:39:06',
                'updated_at' => '2025-08-08 09:39:55',
                'floor_id' => 6,
            ),
            235 => 
            array (
                'id' => 237,
                'name' => '817',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => '2025-08-08 09:39:38',
                'updated_at' => '2025-08-08 09:40:03',
                'floor_id' => 6,
            ),
            236 => 
            array (
                'id' => 238,
                'name' => '812',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => '2025-08-08 09:40:20',
                'updated_at' => '2025-08-08 09:40:20',
                'floor_id' => 6,
            ),
            237 => 
            array (
                'id' => 239,
                'name' => '816',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => '2025-08-08 09:40:37',
                'updated_at' => '2025-08-08 09:40:37',
                'floor_id' => 6,
            ),
            238 => 
            array (
                'id' => 240,
                'name' => '819',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => '2025-08-08 09:41:37',
                'updated_at' => '2025-08-08 09:41:37',
                'floor_id' => 6,
            ),
            239 => 
            array (
                'id' => 241,
                'name' => '824',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => '2025-08-08 09:41:57',
                'updated_at' => '2025-08-08 09:41:57',
                'floor_id' => 6,
            ),
            240 => 
            array (
                'id' => 242,
                'name' => '823',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => '2025-08-08 09:42:18',
                'updated_at' => '2025-08-08 09:42:18',
                'floor_id' => 6,
            ),
            241 => 
            array (
                'id' => 243,
                'name' => '811',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => '2025-08-08 09:42:33',
                'updated_at' => '2025-08-08 09:42:33',
                'floor_id' => 6,
            ),
            242 => 
            array (
                'id' => 245,
                'name' => 'Library - Floor IV',
                'block' => 'E',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => '2025-08-08 10:24:23',
                'updated_at' => '2025-08-08 10:26:08',
                'floor_id' => 6,
            ),
            243 => 
            array (
                'id' => 246,
                'name' => 'Library - Floor III',
                'block' => 'E',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => '2025-08-08 10:25:07',
                'updated_at' => '2025-08-08 10:26:01',
                'floor_id' => 5,
            ),
            244 => 
            array (
                'id' => 247,
                'name' => 'Library - Floor II',
                'block' => 'E',
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => '2025-08-08 10:25:47',
                'updated_at' => '2025-08-08 10:25:47',
                'floor_id' => 4,
            ),
            245 => 
            array (
                'id' => 248,
                'name' => '204',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => '2025-08-08 10:27:09',
                'updated_at' => '2025-08-08 10:27:09',
                'floor_id' => 3,
            ),
            246 => 
            array (
                'id' => 249,
                'name' => 'B-31',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => '2025-08-08 14:22:06',
                'updated_at' => '2025-08-08 14:26:27',
                'floor_id' => 4,
            ),
            247 => 
            array (
                'id' => 250,
                'name' => '831',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => '2025-08-08 14:26:53',
                'updated_at' => '2025-08-08 14:26:53',
                'floor_id' => 6,
            ),
            248 => 
            array (
                'id' => 251,
                'name' => '822',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => '2025-08-08 15:29:11',
                'updated_at' => '2025-08-08 15:29:11',
                'floor_id' => 6,
            ),
            249 => 
            array (
                'id' => 252,
                'name' => '813',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => '2025-08-08 15:29:26',
                'updated_at' => '2025-08-08 15:29:26',
                'floor_id' => 6,
            ),
            250 => 
            array (
                'id' => 253,
                'name' => '21-B',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => '2025-08-08 15:41:26',
                'updated_at' => '2025-08-08 15:41:26',
                'floor_id' => 3,
            ),
            251 => 
            array (
                'id' => 254,
                'name' => 'B-10',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => '2025-08-11 10:43:00',
                'updated_at' => '2025-08-11 10:43:00',
                'floor_id' => 2,
            ),
            252 => 
            array (
                'id' => 255,
                'name' => 'B-39',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => '2025-08-11 13:55:45',
                'updated_at' => '2025-08-11 13:55:45',
                'floor_id' => 4,
            ),
            253 => 
            array (
                'id' => 256,
                'name' => 'B-36',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => '2025-08-12 13:57:35',
                'updated_at' => '2025-08-12 13:57:35',
                'floor_id' => 4,
            ),
            254 => 
            array (
                'id' => 257,
                'name' => 'D-210',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => '2025-08-12 14:47:46',
                'updated_at' => '2025-08-12 14:47:46',
                'floor_id' => 4,
            ),
            255 => 
            array (
                'id' => 258,
                'name' => 'B-46',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 2,
                'created_at' => '2025-08-14 14:11:30',
                'updated_at' => '2025-08-14 14:14:13',
                'floor_id' => 5,
            ),
            256 => 
            array (
                'id' => 259,
                'name' => '804',
                'block' => NULL,
                'is_office' => 1,
                'comment' => NULL,
                'office_location_id' => 1,
                'created_at' => '2025-08-14 15:09:43',
                'updated_at' => '2025-08-21 15:45:57',
                'floor_id' => 6,
            ),
        ));
        
        
    }
}